ACCOUNTS=[
"GC4HL66MPO6LL7ZXAN4NYCMUKSCYSJFXL7JZ4ZFT6IYFKSVC5J3ZQSEU"
]
[[CURRENCIES]]
code="OWLT"
issuer="GC4HL66MPO6LL7ZXAN4NYCMUKSCYSJFXL7JZ4ZFT6IYFKSVC5J3ZQSEU"
display_decimals=0
name="OWL TOKEN"
desc="We Serve OWL Token grind"
image="https://1.bp.blogspot.com/-_ZBgPCP-NH0/Xz0Klauz2aI/AAAAAAAACxI/0mjPdF4ZI0YPZM4XOxf3NloGdUHsCswNgCLcBGAsYHQ/s400/Logo%2BVTube.png"
